#!/bin/bash

set -e

echo '🔄 We will update emsdk to the latest version'

cd /emsdk
./emsdk update
./emsdk install latest
./emsdk activate latest
source ./emsdk_env.sh

if [ ${OPENCV_SOURCE_URL} ]
then
    echo '🌏 We will download OpenCV provided in parameter'
    echo "(OPENCV_SOURCE_URL = ${OPENCV_SOURCE_URL})"

    curl -L -o /tmp/opencv.zip "${OPENCV_SOURCE_URL}"
    rm -rf /opencv/
    mkdir /opencv/
    unzip /tmp/opencv.zip /opencv/
fi

echo '⚙ Now we will build OpenCV.js'

cd /opencv/
python ./platforms/js/build_js.py build_wasm --build_wasm

echo '📦 Copying the production to /built'

cp -r build_wasm/bin/* /built

echo '🎉 Build Finished'
